### ISSUE TITLE
Add time based access levels

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/logcards#8]
We want to allow anyone that has a DoES fob access through the shutter during DoES's normal business hours. Bonus points for using a calendar to block bank holidays.

**Comment by johnmckerrell** [comment]
I just started having a go at the config and came up with this:
```
periods:
    business:
      from: 570 # 9:30
      to: 1050 # 17:30
    maker-day:
      from: 600 # 10:00
      to: 1020 # 17:00
```
Then I realised I was going to need something to specify the days, and that it could get quite complicated with "2nd Saturday in the month". I then thought that really the best option would be to just give the calendar URL and then either have a regex of titles or some marker we put in the calendar. I suspect we'd want this to be a separate calendar to the events calendar so that we could have more control over it though generally it's nicer not to have things in multiple locations at once.

Any thoughts from anyone else?
